# Generated by Django 4.0.2 on 2022-03-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='runData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr1', models.TextField()),
                ('addr2', models.TextField()),
                ('time', models.IntegerField()),
            ],
        ),
    ]
