# Generated by Django 4.0.2 on 2022-03-19 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapIntegration', '0002_route_delete_rundata'),
    ]

    operations = [
        migrations.CreateModel(
            name='runData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('name', models.TextField()),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapIntegration.route')),
            ],
        ),
    ]
