# Generated by Django 4.0.2 on 2022-03-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapIntegration', '0003_rundata'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='routeName',
            field=models.TextField(default=''),
        ),
    ]
