# Generated by Django 4.0.2 on 2022-03-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapIntegration', '0004_route_routename'),
    ]

    operations = [
        migrations.AddField(
            model_name='rundata',
            name='distance',
            field=models.FloatField(default=0),
        ),
    ]
