# Generated by Django 4.0.2 on 2022-03-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapIntegration', '0005_rundata_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='addr1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='route',
            name='addr2',
            field=models.FloatField(),
        ),
    ]
