# Generated by Django 4.0.2 on 2022-03-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapIntegration', '0007_remove_route_addr1_remove_route_addr2'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='addr1Lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='route',
            name='addr1Lng',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='route',
            name='addr2Lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='route',
            name='addr2Lng',
            field=models.FloatField(default=0),
        ),
    ]
